theme: minima

siteConfig:
  url: https://githosted.site
  author: Author of This Site
  email: vasilii@jsmarketing.ru
  description:  Twitter автора проекта: [@saber_land](https://twitter.com/saber_land)

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
    - text: Samples
      link: /samples.html
  social:
    twitter: jsdeveloperpro
    github: githostedsite
    rss: true

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
