theme: minima

siteConfig:
  url: https://githosted.site
  author: Vasilii-Zherar Pavlov
  email: vasilii@jsmarketing.ru
  description: "Twitter автора проекта: https://twitter.com/saber_land"

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
    - text: Samples
      link: /samples.html
  social:
    twitter: jsdeveloperpro
    github: githostedsite
    rss: true

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
